# 301 redirect spring26b -> spring26a
server {
    listen 80;
    server_name spring26b.secoder.net;

    location / {
        return 301 https://pypi-cache-sepi.app.spring26a.secoder.net$request_uri;
    }
}
